export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// STATION TYPES
export const STATION_LOADING = "STATION_LOADING";
export const LOADING_EDIT_STATION = "LOADING_EDIT_STATION";
export const GET_STATIONS = "GET_STATIONS";
export const GET_STATION = "GET_STATION";
export const ADD_STATION = "ADD_STATION";
export const ADD_BIKE_STATION = "ADD_BIKE_STATION";
export const DELETE_STATION = "DELETE_STATION";
export const SEARCH_STATION = "SEARCH_STATION";
export const EDIT_STATION = "EDIT_STATION";
export const UNARCHIVE_STATION = "UNARCHIVE_STATION";
export const ARCHIVE_STATION = "ARCHIVE_STATION";
export const IS_MODIFIED_STATION = "IS_MODIFIED_STATION";

// Mission TYPES
export const MISSION_LOADING = "MISSION_LOADING";
export const LOADING_EDIT_MISSION = "LOADING_EDIT_MISSION";
export const GET_MISSIONS = "GET_MISSIONS";
export const GET_MISSION = "GET_MISSION";
export const ADD_MISSION = "ADD_MISSION";
export const DELETE_MISSION = "DELETE_MISSION";
export const SEARCH_MISSION = "SEARCH_MISSION";
export const EDIT_MISSION = "EDIT_MISSION";
export const UNARCHIVE_MISSION = "UNARCHIVE_MISSION";
export const ARCHIVE_MISSION = "ARCHIVE_MISSION";
export const IS_MODIFIED_MISSION = "IS_MODIFIED_MISSION";

// SLIDER TYPES
export const SLIDER_LOADING = "SLIDER_LOADING";
export const GET_SLIDER = "GET_SLIDER";
export const GET_ALL_SLIDER = "GET_ALL_SLIDER";
export const ADD_SLIDER = "ADD_SLIDER";
export const DELETE_SLIDER = "DELETE_SLIDER";
export const SEARCH_SLIDER = "SEARCH_SLIDER";
export const EDIT_SLIDER = "EDIT_SLIDER";
export const GET_INACTIVE_SLIDER = "GET_INACTIVE_SLIDER";
export const ARCHIVE_SLIDER = "ARCHIVE_SLIDER";
export const UNARCHIVE_SLIDER = "UNARCHIVE_SLIDER";
export const IS_MODIFIED_SLIDER = "IS_MODIFIED_SLIDER";

// BIKE TYPES
export const BIKE_LOADING = "BIKE_LOADING";
export const GET_BIKE = "GET_BIKE";
export const GET_BIKES = "GET_BIKES";
export const ADD_BIKE = "ADD_BIKE";
export const DELETE_BIKE = "DELETE_BIKE";
export const SEARCH_BIKE = "SEARCH_BIKE";
export const EDIT_BIKE = "EDIT_BIKE";
export const GET_INACTIVE_BIKE = "GET_INACTIVE_BIKE";
export const ARCHIVE_BIKE = "ARCHIVE_BIKE";
export const UNARCHIVE_BIKE = "UNARCHIVE_BIKE";
export const IS_MODIFIED_BIKE = "IS_MODIFIED_BIKE";
